### ISSUE TITLE
Unable to use another controller'method in one controller？

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#997]
Unable to use another controller'method in one controller？

like this: 

```
namespace Common\Controller;
use App\Controllers\Login;

class Common extends \CodeIgniter\Controller {
       $login = new Login();
       $login->test();
}
```

and wrong

```
ArgumentCountError
Too few arguments to function CodeIgniter\Controller::__construct(), 0 passed in
```

**Comment by lonnieezell** [comment]
Personally, I'd say what you're doing is bad practice. A controller is specifically meant to control flow through the application from the user's input to returning the response. What you're trying to do is better done in  a separate class. 

That being said, they're just classes. The error should tell you what to look for. There are arguments in the Controller's constructor that it's expecting. If you look at the Controller class itself, you'll see it expects a Request object, a Response object, and a Logger object, IIRC.
